export const goods = [
  {
    id: 1,
    name: 'Canon',
    model: 'PowerShot SX620 HS',
    imageLink: 'camera-1.png',
    priceWorkDay: '630 Р',
    priceRestDay: '750 Р',
    priceWeek: '4 380 Р',
    priceMonth: '12 250 Р',
  },
  {
    id: 2,
    name: 'Canon',
    model: 'PowerShot SX620 HS',
    imageLink: 'camera-2.png',
    priceWorkDay: '630 Р',
    priceRestDay: '750 Р',
    priceWeek: '4 380 Р',
    priceMonth: '12 250 Р',
  },
  {
    id: 3,
    name: 'Canon',
    model: 'PowerShot SX620 HS',
    imageLink: 'camera-3.png',
    priceWorkDay: '630 Р',
    priceRestDay: '750 Р',
    priceWeek: '4 380 Р',
    priceMonth: '12 250 Р',
  },
];